### ISSUE TITLE
cmake files are installed into a wrong location

### ISSUE THREAD

**Issue by yurivict** [materialx/MaterialX#728] opened 2021-10-16 16:29 UTC
They are installed into ```$PREFIX/cmake``` when a standard location is ```$PREFIX/lib/cmake```.

[Here](https://github.com/materialx/MaterialX/blob/main/CMakeLists.txt#L231) and [here](https://github.com/materialx/MaterialX/blob/main/CMakeLists.txt#L234).

**Comment by jstone-lucasfilm** [comment] 2021-10-16 21:22
Good observation, @yurivict, and I can confirm that the OpenEXR project follows the pattern you recommend here, where CMake files are installed into `$CMAKE_INSTALL_PREFIX/lib/cmake`.  I'm adding @bernardkwok to the discussion, since this logic was originally written on the Autodesk side, but the proposed change seems logical to me.

Feel free to put together a pull request for this change if you have the bandwidth; otherwise, we'll take a look on our side once all parties have had a chance to weigh in.

**Comment by jasonliu--** [comment] 2021-10-29 21:10
> IMO this is a very involved and important issue to be left to outside people to submit a PR. Many files of different kind are affected. The project should define an internal variable for the path of all files and update all relevant places accordingly.
> 
> Currently the project just disregards UNIX file layout conventions.

I agree, it's not just the CMake files which disregard the FHS conventions, but rather the entire project. Another example would be the fact that MaterialX places many files into the `resources/` and `libraries/` directories, which MaterialX's build files assume are located in `$CMAKE_INSTALL_PREFIX`. For my MacPorts package, I have to relocate those folders into a directory that conforms to the FHS... in the case of my package, I decided to place them into `/opt/local/share/MaterialX` (MacPorts uses `/opt/local` as its standard installation location; other build systems might use `/usr/local`, etc.). The reason why @yurivict is correct in saying that the overall issue is "very involved" and that "the project should define an internal variable for the path of all files" is because if I change the value of `$CMAKE_INSTALL_PREFIX` at the start of the built, MaterialX will _still_ place everything into `/opt/local/resources` and `/opt/local/libraries`, seemingly ignoring whatever I set `$CMAKE_INSTALL_PREFIX` to (I actually get around the issue by manually moving the `resources/` and `libraries/` directories in to the `share` folder _after_ the output products get generated by MaterialX's build process). In addition, because the MaterialX viewer uses `resources/` and `libraries/` to house its default materials, I actually have to go in and patch the viewer's source code to add `/opt/local/share/MaterialX` to the viewer's default search paths.

MacPorts generally doesn't allow packages that don't conform to the FHS, and all of the workarounds I had to use in order to allow my MacPorts package to follow the FHS are documented in the package spec file for my MaterialX package:

https://github.com/macports/macports-ports/blob/master/graphics/materialx/Portfile

Most of the workarounds are located in the `post-destroot` section, or in the various `variant` sections. If the MaterialX devs want, I'd be willing to file GitHub issues for each of the individual workarounds I had to use.

**Comment by meshula** [comment] 2021-10-30 01:29
We also made the lib/cmake fix in OpenTimelineIO recently. 

Updating the cmake file install location is straight forward and benefits everyone, transparently, aside from having to clean the old ones out from the previous location.

Moving the resource files around is more involved, and can easily have downstream impact on projects that consume MaterialX, such as USD.

I suggest treating the resource files as a separate issue in order to get the obvious cmake config location bugfix straight up, and not gating that on a step that will need more visibility, discussion, and testing.

**Comment by meshula** [comment] 2021-10-30 18:16
instead of hard coding /lib, it should be ${CMAKE_INSTALL_LIB_DIR}, which will resolve where you expect in the OP case, but which can resolve to other places that might differ per a user's native system or build environment conventions. cf https://cmake.org/pipermail/cmake/2012-February/049206.html

**Comment by jasonliu--** [comment] 2021-11-02 20:28
> I suggest treating the resource files as a separate issue in order to get the obvious cmake config location bugfix straight up, and not gating that on a step that will need more visibility, discussion, and testing.

Sorry if I was a bit ambiguous when I brought up the issues regarding `resources/` and `libraries/`; it was only meant to serve as another example of how the locations of MaterialX's output products don't follow FHS conventions. As far as I can tell, `resources/` and `libraries/` is in no way related to the OP's reported issue of the CMake files, and should not be a barrier to fixing the CMake file output location.

**Comment by jstone-lucasfilm** [comment] 2021-11-17 23:57
Thanks to @yurivict for addressing this in #762, and this change is now merged to main.

**Closed by jstone-lucasfilm** 2021-11-17 23:57 UTC
